title: Siddhu's Blog
subtitle: Test
baseurl: "myblog/"
url: "https:/5iddy.github.io/myblog/"
remote_theme: 5iddy/neonnights-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-titles-from-headings

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false 
  
paginate: 5
paginate_path: "/blog/page:num/"
markdown: kramdown


kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
  syntax_highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - webpack.config.js
  - package-lock.json
  - .babelrc

compress_html:
  clippings: all
  ignore:
    envs: development

encoding: "utf-8"